[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[fuzz]
runs = 1024

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

