[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[fuzz]
runs = 1024

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

solc_version="0.8.21"
remappings = [
   "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]   