[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[fuzz]
runs = 1024

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
sepoliaARB = "${SEPOLIA_ARB_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"


[etherscan]
arbiscan = { key = "${ARBITRUM_API_KEY}", chain = 42161 }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

